language: go
go:
 - "1.x"

os: osx

install: true

env:
  global:
    - CODECOV_TOKEN="d9d971f2-368d-46b7-ab06-f605ef2bdb10"

script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)